apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 2090  # Port exposed inside the Kubernetes cluster
      targetPort: 8090  # Port Spring Boot app listens on
  type: LoadBalancer  # Internal service (can change to LoadBalancer or NodePort